# Welcome to Numpy course.

In [1]:
import numpy as np

In [2]:
print("Hello Rohit")

Hello Rohit


In [3]:
import sklearn

In [4]:
i=45

In [5]:
print(7)

7


In [6]:
i

45

In [7]:
# Markdown code First(*Rohit*-tally).Second(**Rohit**-Bold).Third and Four Same(three and Four star use code before name and after).

*Rohit*

**Rohit**

***Rohit***

****Rohit****

In [8]:
myarr=np.array([3,6,32,7])

In [9]:
myarr

array([ 3,  6, 32,  7])

In [10]:
myarr=np.array([3,6,32,7], np.int32)

In [11]:
myarr

array([ 3,  6, 32,  7])

In [12]:
myarr[0]

3

In [13]:
myarr[2]

32

In [14]:
myarr=np.array([[3,6,37,7]], np.int64)

In [15]:
myarr

array([[ 3,  6, 37,  7]], dtype=int64)

In [16]:
myarr[0,0]

3

In [17]:
myarr[0,2]

37

In [18]:
myarr.shape

(1, 4)

In [19]:
myarr.dtype

dtype('int64')

In [20]:
myarr[0,1]=45

In [21]:
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

# Array Creation:Conversion From other Python Structures.

In [22]:
listarray=np.array([1,2,3,4,5,6,7,8,9])

In [23]:
listarray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
listarray.dtype

dtype('int32')

In [27]:
listarray.shape

(3, 3)

In [28]:
listarray.size

9

In [29]:
listarray[1,2]=10

In [30]:
listarray

array([[ 1,  2,  3],
       [ 4,  5, 10],
       [ 7,  8,  9]])

In [31]:
zeros=np.zeros((2,5))

In [32]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
zeros.shape

(2, 5)

In [34]:
zeros.dtype

dtype('float64')

In [35]:
rng=np.arange(15)

In [36]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
lspace=np.linspace(1,5,12)

In [38]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [39]:
lspace=np.linspace(1,4,4)

In [40]:
lspace

array([1., 2., 3., 4.])

In [41]:
emp=np.empty((4,6))

In [42]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06811083e-306, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.69118108e-306],
       [7.56593696e-307, 1.86918699e-306, 1.69120281e-306,
        1.42419802e-306, 1.42419530e-306, 1.24610994e-306],
       [1.69121096e-306, 1.05700515e-307, 1.11261774e-306,
        1.29060871e-306, 8.34424766e-308, 2.12203497e-312]])

In [43]:
emp_like=np.empty_like(lspace)

In [44]:
emp_like

array([1., 2., 3., 4.])

In [45]:
ide=np.identity(45)

In [46]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [47]:
ide.shape

(45, 45)

In [48]:
arr=np.arange(99)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
arr.reshape

<function ndarray.reshape>

In [51]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [52]:
arr=np.arange(6)

In [53]:
arr

array([0, 1, 2, 3, 4, 5])

In [54]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [56]:
arr.shape

(6,)

In [57]:
arr=arr.ravel()

In [58]:
arr

array([0, 1, 2, 3, 4, 5])

In [59]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [60]:
arr=np.arange(1,10)

In [61]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr.sum(axis=0)

45

In [64]:
arr.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr.flat

In [66]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [67]:
arr.ndim

1

In [68]:
arr.size

9

In [69]:
arr.nbytes

36

In [70]:
one=np.arange(1,6)

In [71]:
one.argmax()

4

In [72]:
one.argmin()

0

In [73]:
one.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [74]:
listarray.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [75]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
listarray.argmax()

8

In [77]:
listarray.argmin()

0

In [78]:
listarray.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [79]:
listarray.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [80]:
listarray.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [81]:
listarray.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [82]:
listarray.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [83]:
listarray.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [84]:
listarray.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [85]:
listarray.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
listarray.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
listarray.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [89]:
listarray.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [90]:
listarray2=np.arange(1,10)

In [91]:
listarray2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
listarray+listarray2

ValueError: operands could not be broadcast together with shapes (3,3) (9,) 

In [96]:
[334,4]+[22,4]

[334, 4, 22, 4]

In [94]:
np.sqrt(listarray)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [95]:
listarray.sum()

45

In [97]:
listarray.max()

9

In [98]:
listarray.min()

1

In [99]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
np.where(listarray>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [101]:
type(np.where(listarray<5))

tuple

In [102]:
np.count_nonzero(listarray)

9

In [103]:
np.count_nonzero(arr)

9

In [104]:
np.nonzero(arr)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)

In [105]:
arr[1]=0

In [106]:
np.nonzero(arr)

(array([0, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)

In [107]:
type(np.nonzero(arr))

tuple

In [108]:
import sys

In [109]:
python_array=[0,1,2,3]

In [110]:
Numpy_array=np.array(python_array)

In [112]:
Numpy_array

array([0, 1, 2, 3])

In [111]:
Numpy_array=np.arange(0,4)

In [113]:
Numpy_array

array([0, 1, 2, 3])

In [115]:
sys.getsizeof(1)*len(python_array)

112

In [116]:
Numpy_array.itemsize*Numpy_array.size

16

In [117]:
Numpy_array

array([0, 1, 2, 3])

In [118]:
Numpy_array.tolist()

[0, 1, 2, 3]

In [121]:
Numpy_array.sort()

In [122]:
Numpy_array

array([0, 1, 2, 3])